// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"tweets/internal/biz"
	"tweets/internal/conf"
	"tweets/internal/data"
	"tweets/internal/server"
	"tweets/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	asyncProducer := data.NewKafkaProducer(confData, logger)
	db := data.NewDB(confData, logger)
	client := data.NewCache(confData, logger)
	dataData, cleanup, err := data.NewData(asyncProducer, db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	tweetRepo := data.NewTweetRepo(dataData, logger)
	tweetUsecase := biz.NewTweetUsecase(tweetRepo, logger)
	tweetsService := service.NewTweetsService(tweetUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, tweetsService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
