// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"newsfeeds/internal/biz"
	"newsfeeds/internal/conf"
	"newsfeeds/internal/data"
	"newsfeeds/internal/server"
	"newsfeeds/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	tweetsClient := data.NewTweetsServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, tweetsClient)
	if err != nil {
		return nil, nil, err
	}
	newsFeedRepo := data.NewNewsfeedRepo(dataData, logger)
	newsfeedUsecase := biz.NewGreeterUsecase(newsFeedRepo, logger)
	newsFeedService := service.NewNewsFeedService(newsfeedUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, newsFeedService, logger)
	grpcServer := server.NewGRPCServer(confServer, newsFeedService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, httpServer, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
