trace:
  endpoint: http://127.0.0.1:14268/api/traces
server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:123456@tcp(127.0.0.1:3306)/comments?parseTime=true
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  kafka:
    addrs:
      - 127.0.0.1:9092