// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"friendships/internal/biz"
	"friendships/internal/conf"
	"friendships/internal/data"
	"friendships/internal/server"
	"friendships/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	client := data.NewCache(confData, logger)
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	friendshipRepo := data.NewFriendshipRepo(dataData, logger)
	friendshipUsecase := biz.NewFriendshipUsecase(friendshipRepo, logger)
	friendshipService := service.NewFriendshipService(friendshipUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, friendshipService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
